<?php

namespace ContainerFshXe6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rm2nS_YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rm2nS.Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rm2nS.Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuthorController::CreateAuthor' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\AuthorController::detail' => ['privates', '.service_locator.11tM6JJ', 'get_ServiceLocator_11tM6JJService', true],
            'App\\Controller\\AuthorController::editAuthor' => ['privates', '.service_locator..FMiVxy', 'get_ServiceLocator__FMiVxyService', true],
            'App\\Controller\\AuthorController::show' => ['privates', '.service_locator.hFMYj8t', 'get_ServiceLocator_HFMYj8tService', true],
            'App\\Controller\\BookController::bookCreate' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\BookController::detail' => ['privates', '.service_locator.ViRmCVt', 'get_ServiceLocator_ViRmCVtService', true],
            'App\\Controller\\BookController::editBook' => ['privates', '.service_locator.02qTT3b', 'get_ServiceLocator_02qTT3bService', true],
            'App\\Controller\\BookController::searchBook' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController::show' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController::welcome' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\CategoryBookController::bookCreate' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\CategoryBookController::detail' => ['privates', '.service_locator.y9_dP2H', 'get_ServiceLocator_Y9DP2HService', true],
            'App\\Controller\\CategoryBookController::editCategory' => ['privates', '.service_locator.E87.2VI', 'get_ServiceLocator_E87_2VIService', true],
            'App\\Controller\\CategoryBookController::show' => ['privates', '.service_locator.yxFBDB4', 'get_ServiceLocator_YxFBDB4Service', true],
            'App\\Controller\\CustomerBookController::show' => ['privates', '.service_locator.tAuv_vB', 'get_ServiceLocator_TAuvVBService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AuthorController:CreateAuthor' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\AuthorController:detail' => ['privates', '.service_locator.11tM6JJ', 'get_ServiceLocator_11tM6JJService', true],
            'App\\Controller\\AuthorController:editAuthor' => ['privates', '.service_locator..FMiVxy', 'get_ServiceLocator__FMiVxyService', true],
            'App\\Controller\\AuthorController:show' => ['privates', '.service_locator.hFMYj8t', 'get_ServiceLocator_HFMYj8tService', true],
            'App\\Controller\\BookController:bookCreate' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\BookController:detail' => ['privates', '.service_locator.ViRmCVt', 'get_ServiceLocator_ViRmCVtService', true],
            'App\\Controller\\BookController:editBook' => ['privates', '.service_locator.02qTT3b', 'get_ServiceLocator_02qTT3bService', true],
            'App\\Controller\\BookController:searchBook' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController:show' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\BookController:welcome' => ['privates', '.service_locator.2vrAr7L', 'get_ServiceLocator_2vrAr7LService', true],
            'App\\Controller\\CategoryBookController:bookCreate' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\CategoryBookController:detail' => ['privates', '.service_locator.y9_dP2H', 'get_ServiceLocator_Y9DP2HService', true],
            'App\\Controller\\CategoryBookController:editCategory' => ['privates', '.service_locator.E87.2VI', 'get_ServiceLocator_E87_2VIService', true],
            'App\\Controller\\CategoryBookController:show' => ['privates', '.service_locator.yxFBDB4', 'get_ServiceLocator_YxFBDB4Service', true],
            'App\\Controller\\CustomerBookController:show' => ['privates', '.service_locator.tAuv_vB', 'get_ServiceLocator_TAuvVBService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AuthorController::CreateAuthor' => '?',
            'App\\Controller\\AuthorController::detail' => '?',
            'App\\Controller\\AuthorController::editAuthor' => '?',
            'App\\Controller\\AuthorController::show' => '?',
            'App\\Controller\\BookController::bookCreate' => '?',
            'App\\Controller\\BookController::detail' => '?',
            'App\\Controller\\BookController::editBook' => '?',
            'App\\Controller\\BookController::searchBook' => '?',
            'App\\Controller\\BookController::show' => '?',
            'App\\Controller\\BookController::welcome' => '?',
            'App\\Controller\\CategoryBookController::bookCreate' => '?',
            'App\\Controller\\CategoryBookController::detail' => '?',
            'App\\Controller\\CategoryBookController::editCategory' => '?',
            'App\\Controller\\CategoryBookController::show' => '?',
            'App\\Controller\\CustomerBookController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AuthorController:CreateAuthor' => '?',
            'App\\Controller\\AuthorController:detail' => '?',
            'App\\Controller\\AuthorController:editAuthor' => '?',
            'App\\Controller\\AuthorController:show' => '?',
            'App\\Controller\\BookController:bookCreate' => '?',
            'App\\Controller\\BookController:detail' => '?',
            'App\\Controller\\BookController:editBook' => '?',
            'App\\Controller\\BookController:searchBook' => '?',
            'App\\Controller\\BookController:show' => '?',
            'App\\Controller\\BookController:welcome' => '?',
            'App\\Controller\\CategoryBookController:bookCreate' => '?',
            'App\\Controller\\CategoryBookController:detail' => '?',
            'App\\Controller\\CategoryBookController:editCategory' => '?',
            'App\\Controller\\CategoryBookController:show' => '?',
            'App\\Controller\\CustomerBookController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
