<?php

namespace ContainerFshXe6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.02qTT3b.App\Entity\Book' shared service.
     *
     * @return \App\Entity\Book
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.02qTT3b": it references class "App\\Entity\\Book" but no such service exists.');
    }
}
