<?php

namespace ContainerFshXe6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.E87.2VI.App\Entity\CategoryBook' shared service.
     *
     * @return \App\Entity\CategoryBook
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.E87.2VI": it references class "App\\Entity\\CategoryBook" but no such service exists.');
    }
}
