<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFshXe6b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFshXe6b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFshXe6b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFshXe6b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFshXe6b\App_KernelDevDebugContainer([
    'container.build_hash' => 'FshXe6b',
    'container.build_id' => '283ec08d',
    'container.build_time' => 1698258164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFshXe6b');
