<?php

namespace ContainerK9oItGx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ViRmCVtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ViRmCVt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ViRmCVt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'books' => ['privates', '.errored..service_locator.ViRmCVt.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.ViRmCVt": it references class "App\\Entity\\Book" but no such service exists.'],
        ], [
            'books' => 'App\\Entity\\Book',
        ]);
    }
}
